name: pod_router
description: "A Flutter navigation package that combines go_router with Riverpod for clean, testable routing with authentication support."
version: 0.0.1+2
# homepage: https://github.com/1farz1/pod_router
# repository: https://github.com/yourusername/pod_router
# issue_tracker: https://github.com/yourusername/pod_router/issues
# documentation: https://github.com/yourusername/pod_router#readme
license: MIT

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - navigation
  - routing
  - riverpod
  - go-router
  - authentication

flutter: